### ISSUE TITLE
google drive file doesn't exist anymore

### ISSUE THREAD

**Issue by khuechuong** [zkytony/cos-pomdp#15]
These links for zips no longer exist so I can't download them:

yolov5-training-data.zip, yolov5-detectors.zip, corrs.zip

https://drive.google.com/uc?id=1V0GC3wyTsrEAaDfXR0ZyGWLY4j2hYMsx
https://drive.google.com/uc?id=1gfgtLgyLpYa0YLsHkpBF2YWioHR3_ilw
https://drive.google.com/uc?id=1uKekHoUcIOKPuVfD02YzYTk908SeGKbm

**Comment by khuechuong** [comment]
@RajeshDM do you still have the zips?

**Comment by zkytony** [comment]
@khuechuong Just fixed. Not yet tested. Let me know if they work for you.
The links broke since my university google drive is gone after I graduated.

**Comment by khuechuong** [comment]
yolov5-training-data.zip and corrs.zip worked, but yolov5-detectors.zip isn't.

**Comment by zkytony** [comment]
@khuechuong try again? should work now. I forgot to turn on permission for yolov5-detectors.zip.

**Comment by khuechuong** [comment]
got it! thx!

**Comment by RajeshDM** [comment]
I think the links are still broken - I tried downloading and it says page not found

**Comment by zkytony** [comment]
I just tried. Worked for me.

**Comment by RajeshDM** [comment]
I actually tried it from multiple systems and got the same 404 error (both for access through browser and download.py). Is it possible there are some permission issues? my email is rajeshdm9@gmail.com - it would be great if I could get access to them

**Comment by zkytony** [comment]
If @khuechuong gets them, you should be able to as well. I tried accessing in incognito mode.

Are you sure you are visiting the links in [download.py](https://github.com/zkytony/cos-pomdp/blob/master/download.py)?

**Comment by RajeshDM** [comment]
Ok it's working now. Thank you. looks like my download.py file was corrupted for some reason. Its working after a fresh install. Thank you. 
Also, I was wondering  - for the detectors - I see that you are using YoloV5 - but do you retrain the learned models a little for the obejcts in AI2Thor that were not in the Yolo Object set? and if so, is that code available somewhere?
